### ISSUE TITLE
workflow一直是一个状态

### ISSUE THREAD

**Issue by zjhzjhhh** [taropowder/pokemonscan-pokeball#2]
师傅你好，前一天加的资产扫描，过了一天还是在domian状态是为什么呀
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/64487620/221745583-bf4f89da-eb0c-41b0-909b-3ae247b1719e.png">
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/64487620/221745584-9772b437-f179-455c-a2f6-48aa3c653c12.png">

**Comment by taropowder** [comment]
师傅可以看下是否正确生成task任务，以及task内的任务是否工作完毕
我看 "input" 阶段配置是 EnScan , EnScan 的输入应该是一个公司名，求review下workflow 输入的内容是否是公司名。
Enscan 如果执行成功会在附加信息增加APK、备案的一些信息 + domain 根域名，如果这些信息都没有，说明 Input 阶段没有执行成功， domain 阶段没有domain 参数，所以被卡到这里
