### ISSUE TITLE
bash install报错

### ISSUE THREAD

**Issue by zjhzjhhh** [taropowder/pokemonscan-pokeball#3]
重装了一遍，系统centos8.2，后面也会提示success init admin user ，但是会报这个错误
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/64487620/222094851-83b0ebc4-1740-4f72-8b5a-284d0f3b0932.png">

**Comment by taropowder** [comment]
啊不是错误（捂脸）打的log，可能引起误解了

**Comment by zjhzjhhh** [comment]
感谢师傅！ https://github.com/taropowder/pokemonscan-pokeball/issues/2也解决了，一会close。
另外还有一个问题，enscan目前是只支持aqc嘛，可以自定type加其他的嘛

**Comment by taropowder** [comment]
当前enscan的submodule commit是我当时为了快速跑起来给提的pr，临时加了个json输出功能，根据我的测试好像能用的只有 aqc 和 tyc， 其他的查询方式我没查成功，我看最近原作更新了，规范了json输出，最近有时间再做一下解析。
另外，对于tyc，我测试发现如果在云服务上跑会被ban，建议后面跟一个proxy插件【画个饼，还在开发中】或者是把worker放在家里的网跑这个插件。

**Comment by taropowder** [comment]
文档在这里
https://pokemonscan.github.io/#/zh-cn/%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E/plugins_config?id=enscan

**Comment by zjhzjhhh** [comment]
感谢师傅！最后一个问题，oneforlall 中的配置文件 api.py可以给一个配置案例嘛格式之类的，里面有很多api

**Comment by taropowder** [comment]
https://pokemonscan.github.io/#/zh-cn/%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E/plugins_config?id=oneforall
更新了一下文档，其实就是把原仓库 https://github.com/shmilylty/OneForAll/blob/master/config/api.py 的文件base64
后续原仓库更新也只需更新api.py 😁

**Comment by taropowder** [comment]
之前考虑过加个扫端口（所以预留了一个host阶段），测了一下感觉不如接到fofa这种资产测绘上😂自己扫的成本还是比较高，后续打算先缝一下`nmap`,`,`msscan`。
`fscan` 这种内网杀器 1.0 暂不会加入，不过在后续有计划做内网版本，会脱离容器依赖，在内网中以workflow的模式进行蠕虫式扩散，不过1.0的坑实在是太多，估计要填个一年半载的😭。

**Comment by taropowder** [comment]
> 感谢师傅！ 后续可以添加一个msscan或者nmap这种扫全端口的插件嘛 fscan等

已将nmap 和 msscan 加入疯狂星期四😂，并服务端做了些适配，师傅可以试一下
 [端口扫描实践](https://pokemonscan.github.io/#/zh-cn/%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/port_scan)
直接这样拉取最新服务端镜像，对所有worker重启一次即可
[服务端更新](https://pokemonscan.github.io/#/zh-cn/%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B/update)

**Comment by zjhzjhhh** [comment]
师傅你好，请问可以输入域名作为内容嘛，我这边试过删除enscan插件，添加域名的话会报错。

**Comment by taropowder** [comment]
> 师傅你好，请问可以输入域名作为内容嘛，我这边试过删除enscan插件，添加域名的话会报错。

诶，可以的呀，预期上任何都可以作为输入，话说报了什么错
