### ISSUE TITLE
扫描不了 wuwuwuwuwu...

### ISSUE THREAD

**Issue by zjhzjhhh** [taropowder/pokemonscan-pokeball#5]
直接上图
![image](https://user-images.githubusercontent.com/64487620/227112442-0048343c-63db-48c1-9736-03caf3aa0bb0.png)
![image](https://user-images.githubusercontent.com/64487620/227112521-4e2fdc61-8f58-4d9a-9146-33116337f93c.png)
![image](https://user-images.githubusercontent.com/64487620/227114035-86778a97-4f74-4afe-a14c-e135b0437703.png)

![image](https://user-images.githubusercontent.com/64487620/227112721-e6c80e41-ba59-4a9e-b227-219c999948bf.png)
然后安装worker的时候会报这个错误
![image](https://user-images.githubusercontent.com/64487620/227113558-bfe65d37-bbd7-4969-bfbf-e798b30ce458.png)
在worker列表里面没有运行的worker
![image](https://user-images.githubusercontent.com/64487620/227112776-52d2cb74-acda-4dcc-b326-56754f283b22.png)

**Comment by taropowder** [comment]
看起来是覆盖安装的问题，师傅可以把 `/opt/pokeball/` 目录删掉再试试 😭

**Comment by zjhzjhhh** [comment]
删过重新curl了的，然后一只不太行就重新装了下系统，现在ecs是ubuntu。 wuwuwuwuwuwuwu

**Comment by taropowder** [comment]
可以这样确定worker是否工作正常
`ps -ef | grep pokeball`
如果存在 `/opt/pokeball/bin/pokeball run -s xxxxx:9213` 进程说明worker正常工作。如果此时服务端还是没有worker成功注册，查看系统日志
`journalctl -f -u pokeball`

如果有报错，师傅您也可以加一下扣扣群发我下详细报错，反馈快一些
![image](https://user-images.githubusercontent.com/31129902/227119955-a8cf0000-efd4-4f96-adcf-720fcbe4bca0.png)
